background {
    monitor =
    path    = /home/mboaisha/Pictures/blue-background.jpg # Needs to be changed
    blur_passes = 2
    blur_size   = 7
}

general {
    hide_cursor = true
    grace       = 0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size         = 0.33
    dots_spacing      = 0.15
    dots_center       = true
    outer_color       = rgba(0, 0, 0, 0)
    inner_color       = rgba(0, 0, 0, 0.5)
    font_color        = rgb(cdd6f4)
    fade_on_empty     = true
    placeholder_text  = <i>Password...</i>
    position          = 0, -120
    halign            = center
    valign            = center
}

label {
    monitor  =
    text     = cmd[update:1000] echo "<b><big>$(date +'%H:%M')</big></b>"
    color    = rgba(205, 214, 244, 1.0)
    font_size = 90
    font_family = Source Code Pro
    position = 0, 80
    halign   = center
    valign   = center
}

label {
    monitor =
    text    = $USER
    color   = rgba(205, 214, 244, 0.8)
    font_size = 18
    font_family = Source Code Pro
    position = 0, -60
    halign   = center
    valign   = center
}
