background        = 0xFF000000  # bg-main
base              = 0xFF1E1E1E  # bg-dim
alternate_base    = 0xFF2B2B2B  # bg-alt
text              = 0xFFFFFFFF  # fg-main
bright_text       = 0xFFFFFFFF  # fg-main
accent            = 0xFF2FAFFF  # blue
accent_secondary  = 0xFFFEACD0  # magenta